### ISSUE TITLE
Allows to escape SWVBResponseCallBack

### ISSUE THREAD

**Issue by sylvainlaurent** [ShawnFoo/SwiftWebViewBridge#10]
When some JS calls my Swift handler with a SWVBResponseCallBack, I want to use this callback after an async call returns. But the Swift compiler complains about "Closure use of non-escaping parameter...."

Therefore I propose to have SWVBHandler declared like this:
```swift
public typealias SWVBHandler = (AnyObject, @escaping SWVBResponseCallBack) -> Void
```
instead of 
```swift
public typealias SWVBHandler = (AnyObject, SWVBResponseCallBack) -> Void
```

**Comment by ShawnFoo** [comment]
Thanks, Good point!
