### ISSUE TITLE
ERROR in webView:didFailLoadWithError:

### ISSUE THREAD

**Issue by libern** [ShawnFoo/SwiftWebViewBridge#2]
```
func webView(webView: UIWebView, didFailLoadWithError error: NSError?) {
        print("Failed to load")
        print(error?.localizedDescription)
}
```

This function will print error message every time when iframe's source changed

```
The URL can’t be shown:
swvbscheme://__SWVB_Host_MESSAGE__
```

**Comment by ShawnFoo** [comment]
Thanks.
Since I forgot to **return false** in the method
- webView:shouldStartLoadWithRequest:navigationType:

This will be fixed in next commit.
