### ISSUE TITLE
when handler an unknow meth handlerName fatalError

### ISSUE THREAD

**Issue by 419860198** [ShawnFoo/SwiftWebViewBridge#21]
2018-02-01 14:17:25.014586+0800 Sellers[338:53387] Fatal error: No handler for msg from JS: ["callbackId": cb_2_JS_1517465828437, "handlerName": getUnreadNum, "data": {
}]..Please at least create a default handler when initializing the bridge = ): file /Users/zhangxiaobo/TFotomerchanat/Pods/SwiftWebViewBridge/SwiftWebViewBridge/SwiftWebViewBridge.swift, line 223

can you don't use fatalError?

**Comment by ShawnFoo** [comment]
Yep, I totally agree with you. 

A typo in javascript will crash the app. That's unacceptable.

That will be changed to print debug log or only using fatalError in debug mode.

**Comment by ShawnFoo** [comment]
Already removed fatalError on branch develop_wkwebview
