### ISSUE TITLE
CocoaPods Issue

### ISSUE THREAD

**Issue by schayes04** [ShawnFoo/SwiftWebViewBridge#8]
The update with Swift 3 was not pushed to the CocoaPods Specs, so it is unable to be installed via CocoaPods. Can you update this?

**Comment by schayes04** [comment]
I also see you are missing a swift-version file, I have created a PR for that. Can you merge before updating the CocoaPod?

**Comment by ShawnFoo** [comment]
Thanks, @schayes04 
Already updated Cocoapod.
